import shlex

from paperext.config import CFG


def parse_curl():
    """Parse curl_tokens generated by the output of Firefox Copy as cURL
    https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/request_list/index.html#context-menu
    """
    cmd, url, *curl_options = shlex.split(
        (CFG.dir.paperoni / "curl_tokens").read_text()
    )

    assert cmd == "curl"
    assert url.startswith(CFG.paperoni.url)

    return curl_options
